FROM python:3.13-slim as builder

RUN  mkdir /app

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/


RUN pip install --upgrade pip && \
    pip install --prefix=/install -r requirements.txt


FROM python:3.13-slim as production
WORKDIR /app


COPY --from=builder /install /usr/local


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . .

CMD ["python","manage.py","runserver","0.0.0.0:8000"]