# Generated by Django 6.0.3 on 2026-04-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
